export const INIT = "INIT"

export const CURRENT_VALUE="CURRENT_VALUE"
export const INCREMENT_CURRENT_VALUE="INCREMENT_CURRENT_VALUE"

export const UPDATE_PER_CLICK="UPDATE_PER_CLICK"
export const UPDATE_PER_SECONDS="UPDATE_PER_SECONDS"
export const UPDATE_PER_SECONDS_VALUE="UPDATE_PER_SECONDS_VALUE"
